### ISSUE TITLE
dual monitor not working

### ISSUE THREAD

**Issue by kevinhwang91** [velitasali/GTKTitleBar#5]
when using dual monitor, only primary monitor work but not secondary.

**Comment by velitasali** [comment]
@kevinhwang91 I don't own a second second monitor, so I don't know how it looks on a secondary monitor.

As far as I remember, you don't get another top bar (not title bar) within it, so you would not be able close the windows without unmaximazing using keyboard shortcuts.

If it is not the case, I will try try to add an option for it in my free time.

**Comment by kevinhwang91** [comment]
the result is the primary monitor can hide the title bar, but the secondary can't. Even move primary monitor window(some program) is already hidden to the secondary monitor, when focus the window, the title bar displays again in secondary monitor.
It's seen that the plugin doesn't work at  secondary monitor.
I

**Comment by MateuszKubuszok** [comment]
The same issue happens in https://github.com/hardpixel/unite-shell - from all solutions I tested only https://github.com/franglais125/no-title-bar had it solved, but no-title-bar stopped working after 3.32 update. Maybe the fix could be figured by comparing the solutions.

**Comment by MateuszKubuszok** [comment]
I tested that in my case worked [this CSS](https://joshtronic.com/2017/07/26/hide-title-bars-in-gnome-shell/) - I just changed `windows.ssd` to `window.ssd.maximized` and now I have title bar removed in all monitors:

```css
window.ssd.maximized separator:first-child + headerbar:backdrop,
window.ssd.maximized separator:first-child + headerbar,
window.ssd.maximized headerbar:first-child:backdrop,
window.ssd.maximized headerbar:first-child,
window.ssd.maximized headerbar:last-child:backdrop,
window.ssd.maximized headerbar:last-child,
window.ssd.maximized stack headerbar:first-child:backdrop,
window.ssd.maximized stack headerbar:first-child,
window.ssd.maximized stack headerbar:last-child:backdrop,
window.ssd.maximized stack headerbar:last-child,
window.ssd.maximized decoration,
window.ssd.maximized headerbar.titlebar {
  border-radius: 0;
}


window.ssd.maximized headerbar * {
  margin-top: -100px;
  color: #1c2022;
}


window.ssd.maximized headerbar.titlebar,
window.ssd.maximized headerbar.titlebar button.titlebutton {
  border: none;
  font-size: 0;
  height: 0;
  margin: 0;
  max-height: 0;
  min-height: 0;
  padding: 0;
}
```

I am certain that there is redundancy in this CSS, but I can tell that it worked for me in this form. The only issue is that non-maximized windows have title bars with no text but I can live with that.
